language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - '6'
  - '8'
notifications:
  email: false
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
services:
  - redis-server
